spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    jpa:
        show-sql: true # true 설정시 JPA 쿼리문 확인 가능
        hibernate:
            ddl-auto: create-drop # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
        properties:
            hibernate:
                format_sql: true # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
    profiles:
        active: local
        group:
            "local": "local, key"
            "dev": "dev, key"