spring:
    config:
        activate:
            on-profile: local
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    jpa:
        show-sql: true # true 설정시 JPA 쿼리문 확인 가능
        hibernate:
            ddl-auto: none # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
        properties:
            hibernate:
                format_sql: true # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
        open-in-view: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tink?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root #임시
        password: ssafy

server:
    port: 8081
    servlet:
        context-path: /tink

app:
    auth:
        oauth2:
            authorizedRedirectUri: http://localhost:9999/oauth2/redirect
    upload:
        folder: C:\S08P22C201\tink\image

logging:
    level:
        web: info
        root: debug