spring:
    config:
        activate:
            on-profile: local
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher     # swagger 2.6.x부터 pathmatch가 변경되어 ' ant_path_matcher'를 주입
    jpa:
        show-sql: true # true 설정시 JPA 쿼리문 확인 가능
        hibernate:
            ddl-auto: none # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
            use-new-id-generator-mappings: false
        properties:
            hibernate:
                format_sql: true # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
        open-in-view: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver             # DB driver를 설정
        url: jdbc:mysql://localhost:3306/tink?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: ssafy  # 유저ID
        password: ssafy # 유저PW
    data:
        redis:
            host: localhost
            port: 6379
    session:
        store-type: redis

server:
    port: 8081              # 서비스 포트지정
    servlet:
        context-path: /     # contextPaht를 지정하면 기본 uri가 지정된다.

app:
    auth:
        oauth2:
            authorizedRedirectUri: http://localhost:8081/oauth2/redirect     # Token을 받을 Url를 지정
    upload:
        folder: C:\S08P22C201\tink\image      # 파일이 저장될 경로 설정
#        folder: /Users/junyoungpark/Downloads      # 파일이 저장될 경로 설정

logging:
    level:
        web: INFO
        com: INFO
        root: INFO