spring:
  profiles:
    group:
      "local": "local, key"
      "dev": "dev, key"
      "test": "test, key"
    active: dev
  servlet:
    multipart:
      #file upload size
      max-file-size: 3MB
